"""Initial migration for SQLite

Revision ID: 8d174e55a199
Revises: 
Create Date: 2026-03-16 20:43:05.679516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d174e55a199'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ksef_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('session_type', sa.String(length=20), nullable=False),
    sa.Column('reference_number', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('upo_reference_number', sa.String(length=255), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ksef_sessions')),
    sa.UniqueConstraint('reference_number', name='uq_ksef_sessions__reference_number')
    )
    op.create_index(op.f('ix_ksef_sessions__ksef_sessions_company_id'), 'ksef_sessions', ['company_id'], unique=False)
    op.create_index(op.f('ix_ksef_sessions__ksef_sessions_environment'), 'ksef_sessions', ['environment'], unique=False)
    op.create_index(op.f('ix_ksef_sessions__ksef_sessions_session_type'), 'ksef_sessions', ['session_type'], unique=False)
    op.create_index(op.f('ix_ksef_sessions__ksef_sessions_status'), 'ksef_sessions', ['status'], unique=False)
    op.create_table('ksef_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ksef_tokens')),
    sa.UniqueConstraint('company_id', 'environment', name='uq_ksef_tokens__company_environment')
    )
    op.create_index(op.f('ix_ksef_tokens__ksef_tokens_company_id'), 'ksef_tokens', ['company_id'], unique=False)
    op.create_table('ksef_invoice_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('session_reference_number', sa.String(length=255), nullable=False),
    sa.Column('local_invoice_number', sa.String(length=255), nullable=False),
    sa.Column('ksef_invoice_reference', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('xml_hash_sha256', sa.String(length=128), nullable=True),
    sa.Column('upo_content', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_reference_number'], ['ksef_sessions.reference_number'], name='fk_ksef_invoice_submissions__session_reference_number__ksef_sessions'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ksef_invoice_submissions'))
    )
    op.create_index(op.f('ix_ksef_invoice_submissions__ksef_invoice_submissions_company_id'), 'ksef_invoice_submissions', ['company_id'], unique=False)
    op.create_index(op.f('ix_ksef_invoice_submissions__ksef_invoice_submissions_environment'), 'ksef_invoice_submissions', ['environment'], unique=False)
    op.create_index(op.f('ix_ksef_invoice_submissions__ksef_invoice_submissions_ksef_invoice_reference'), 'ksef_invoice_submissions', ['ksef_invoice_reference'], unique=False)
    op.create_index(op.f('ix_ksef_invoice_submissions__ksef_invoice_submissions_local_invoice_number'), 'ksef_invoice_submissions', ['local_invoice_number'], unique=False)
    op.create_index(op.f('ix_ksef_invoice_submissions__ksef_invoice_submissions_session_reference_number'), 'ksef_invoice_submissions', ['session_reference_number'], unique=False)
    op.create_index(op.f('ix_ksef_invoice_submissions__ksef_invoice_submissions_status'), 'ksef_invoice_submissions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ksef_invoice_submissions__ksef_invoice_submissions_status'), table_name='ksef_invoice_submissions')
    op.drop_index(op.f('ix_ksef_invoice_submissions__ksef_invoice_submissions_session_reference_number'), table_name='ksef_invoice_submissions')
    op.drop_index(op.f('ix_ksef_invoice_submissions__ksef_invoice_submissions_local_invoice_number'), table_name='ksef_invoice_submissions')
    op.drop_index(op.f('ix_ksef_invoice_submissions__ksef_invoice_submissions_ksef_invoice_reference'), table_name='ksef_invoice_submissions')
    op.drop_index(op.f('ix_ksef_invoice_submissions__ksef_invoice_submissions_environment'), table_name='ksef_invoice_submissions')
    op.drop_index(op.f('ix_ksef_invoice_submissions__ksef_invoice_submissions_company_id'), table_name='ksef_invoice_submissions')
    op.drop_table('ksef_invoice_submissions')
    op.drop_index(op.f('ix_ksef_tokens__ksef_tokens_company_id'), table_name='ksef_tokens')
    op.drop_table('ksef_tokens')
    op.drop_index(op.f('ix_ksef_sessions__ksef_sessions_status'), table_name='ksef_sessions')
    op.drop_index(op.f('ix_ksef_sessions__ksef_sessions_session_type'), table_name='ksef_sessions')
    op.drop_index(op.f('ix_ksef_sessions__ksef_sessions_environment'), table_name='ksef_sessions')
    op.drop_index(op.f('ix_ksef_sessions__ksef_sessions_company_id'), table_name='ksef_sessions')
    op.drop_table('ksef_sessions')
    # ### end Alembic commands ###
